/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.bd.sistema.gui;

import br.edu.ifnmg.bd.sistema.dao.LineUpDao;
import br.edu.ifnmg.bd.sistema.dao.RelatorioBandaDao;
import br.edu.ifnmg.bd.sistema.dao.RelatorioLineUpDao;
import br.edu.ifnmg.bd.sistema.entity.LineUp;
import br.edu.ifnmg.bd.sistema.entity.RelatorioBanda;
import br.edu.ifnmg.bd.sistema.entity.RelatorioLineUp;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author annaj
 */
public class TelaRelatorioLineUp extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatorioLineUp
     */
    public TelaRelatorioLineUp() {
        initComponents();
        LineUpDao dao = new LineUpDao();
        for (LineUp l : dao.read()) {
            cbRelatorio.addItem(l);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRelatorioLineUp = new javax.swing.JButton();
        cbRelatorio = new javax.swing.JComboBox<>();
        btnBandaRelatorio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRelatorioLineUp.setText("Gerar Pdf");
        btnRelatorioLineUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioLineUpActionPerformed(evt);
            }
        });

        cbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRelatorioActionPerformed(evt);
            }
        });

        btnBandaRelatorio.setText("Gerar Pdf");
        btnBandaRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBandaRelatorioActionPerformed(evt);
            }
        });

        jLabel1.setText("Gerar PDF das Line-ups: ");

        jLabel2.setText("Gerar PDF das bandas:");

        jLabel3.setText("Selecione uma data:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBandaRelatorio))
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRelatorioLineUp)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnRelatorioLineUp))
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBandaRelatorio))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(607, 249));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRelatorioLineUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioLineUpActionPerformed
        // TODO add your handling code here:
        Document doc = new Document();

        RelatorioLineUpDao relat = new RelatorioLineUpDao();

        try {

            try {
                PdfWriter.getInstance(doc, new FileOutputStream("C:/Users/annaj/Desktop/Arquivos/Faculdade/2020 - 2/BD/Projeto pratico 5/Relatorio/teste.pdf"));
                doc.open();
                for (RelatorioLineUp r : relat.procurar()) {

                    doc.add(new Paragraph(r.toString()));
                }
                doc.close();
            } catch (DocumentException ex) {
                Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnRelatorioLineUpActionPerformed

    private void cbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRelatorioActionPerformed

    private void btnBandaRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBandaRelatorioActionPerformed
        // TODO add your handling code here:
        Document doc = new Document();
        LineUp lu = (LineUp) cbRelatorio.getSelectedItem();
        RelatorioBandaDao relat = new RelatorioBandaDao();
        try {
            try {
                PdfWriter.getInstance(doc, new FileOutputStream("C:/Users/annaj/Desktop/Arquivos/Faculdade/2020 - 2/BD/Projeto pratico 5/Relatorio/Relatorio Banda.pdf"));
                doc.open();
                for (RelatorioBanda r : relat.procurar(lu.getData())) {

                    doc.add(new Paragraph(r.toString()));
                }
                doc.close();
            } catch (DocumentException ex) {
                Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBandaRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioLineUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioLineUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBandaRelatorio;
    private javax.swing.JButton btnRelatorioLineUp;
    public static javax.swing.JComboBox<Object> cbRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
