package br.edu.ifnmg.bd.sistema.gui;

import br.edu.ifnmg.bd.sistema.dao.IngressoDao;
import br.edu.ifnmg.bd.sistema.dao.LineUpDao;
import br.edu.ifnmg.bd.sistema.entity.Ingresso;
import br.edu.ifnmg.bd.sistema.entity.LineUp;


public class TelaAtualizarIngresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaArualizarIngresso
     */
    public TelaAtualizarIngresso() {
        initComponents();
        IngressoDao dao = new IngressoDao();
        for (Ingresso i : dao.read()) {
            cbAtualizarIngresso.addItem(i);
        }
        LineUpDao ldao = new LineUpDao();
        for (LineUp l : ldao.read()) {
            cbAtualizarData.addItem(l);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbAtualizarIngresso = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtAtualizarValor = new javax.swing.JTextField();
        cbAtualizarData = new javax.swing.JComboBox<>();
        txtAtualizarHora = new javax.swing.JTextField();
        txtAtualizarEspectador = new javax.swing.JTextField();
        btnAtualizarIngresso = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cbAtualizarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAtualizarIngressoActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor:");

        jLabel2.setText("Data Line-up:");

        jLabel3.setText("Hora Entrada:");

        jLabel4.setText("Cpf Espectador:");

        txtAtualizarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAtualizarValorActionPerformed(evt);
            }
        });

        btnAtualizarIngresso.setText("Atualizar");
        btnAtualizarIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarIngressoActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecione:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAtualizarEspectador)
                                    .addComponent(txtAtualizarHora)
                                    .addComponent(cbAtualizarData, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbAtualizarIngresso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAtualizarValor)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(245, 245, 245)
                .addComponent(btnAtualizarIngresso)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAtualizarIngresso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAtualizarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAtualizarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAtualizarHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAtualizarEspectador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnAtualizarIngresso)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(591, 340));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbAtualizarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAtualizarIngressoActionPerformed
        // TODO add your handling code here:
        Ingresso i = (Ingresso) cbAtualizarIngresso.getSelectedItem();
        Ingresso ii = new IngressoDao().consultar(i);
        LineUpDao ldao = new LineUpDao();
        for (LineUp l : ldao.read()) {
            if(l.getData().equals(ii.getPertencedatalineup())){
                cbAtualizarData.getModel().setSelectedItem(l);
            }            
        }

        txtAtualizarValor.setText(ii.getValor());
        txtAtualizarHora.setText(ii.getHoraEntrada());
        txtAtualizarEspectador.setText(ii.getCpfespectador());
    }//GEN-LAST:event_cbAtualizarIngressoActionPerformed

    private void txtAtualizarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAtualizarValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAtualizarValorActionPerformed

    private void btnAtualizarIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarIngressoActionPerformed
        // TODO add your handling code here:
        Ingresso i = (Ingresso) cbAtualizarIngresso.getSelectedItem();
        LineUp l = (LineUp) cbAtualizarData.getSelectedItem();
        
        Ingresso ig = new Ingresso();
        
        ig.setNumero(i.getNumero());
        ig.setCpfespectador(txtAtualizarEspectador.getText());
        ig.setPertencedatalineup(l.getData());
        ig.setHoraEntrada(txtAtualizarHora.getText());
        if(ig.getHoraEntrada().isEmpty()){
            ig.setDataLineupEntrada(ig.getHoraEntrada());
        }else{
            ig.setDataLineupEntrada(l.getData());
        }
        ig.setValor(txtAtualizarValor.getText());

        new IngressoDao().atualizar(ig);
    }//GEN-LAST:event_btnAtualizarIngressoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAtualizarIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAtualizarIngresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizarIngresso;
    public static javax.swing.JComboBox<Object> cbAtualizarData;
    public static javax.swing.JComboBox<Object> cbAtualizarIngresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtAtualizarEspectador;
    private javax.swing.JTextField txtAtualizarHora;
    private javax.swing.JTextField txtAtualizarValor;
    // End of variables declaration//GEN-END:variables
}
