/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.bd.sistema.gui;

import br.edu.ifnmg.bd.sistema.dao.BandaDao;
import br.edu.ifnmg.bd.sistema.dao.IngressoDao;
import br.edu.ifnmg.bd.sistema.dao.LineUpDao;
import br.edu.ifnmg.bd.sistema.dao.PessoaDao;
import br.edu.ifnmg.bd.sistema.dao.ShowDao;
import br.edu.ifnmg.bd.sistema.entity.Banda;
import br.edu.ifnmg.bd.sistema.entity.Ingresso;
import br.edu.ifnmg.bd.sistema.entity.LineUp;
import br.edu.ifnmg.bd.sistema.entity.Pessoa;
import br.edu.ifnmg.bd.sistema.entity.Show;
import static br.edu.ifnmg.bd.sistema.gui.TelaAdicionarPessoa.txtAddPessoaTipo;
import static br.edu.ifnmg.bd.sistema.gui.TelaSelecionarLineUp.cbselecionarBandas;
import static br.edu.ifnmg.bd.sistema.gui.TelaSelecionarLineUp.cbselecionarShows;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author annaj
 */
public class TelaInserirIngresso extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionarIngresso
     */
    public TelaInserirIngresso() {
        initComponents();
        LineUpDao daoLineUp = new LineUpDao();
        for(LineUp l: daoLineUp.read()){
            cbAdicionarData.addItem(l);      
        }
        PessoaDao daoPessoa = new PessoaDao();
        for(Pessoa p: daoPessoa.readEspectador()){
            cbAdicionarEspectador.addItem(p);      
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbAdicionarEspectador = new javax.swing.JComboBox<>();
        cbAdicionarData = new javax.swing.JComboBox<>();
        txtAdicionarHora = new javax.swing.JTextField();
        txtAdicionarValor = new javax.swing.JTextField();
        btnInserirIngresso = new javax.swing.JButton();
        btnInserirVerInformacoes = new javax.swing.JButton();
        btnInserirCadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Valor");

        jLabel2.setText("Data Line-Up");

        jLabel3.setText("Hora Entrada");

        jLabel4.setText("Cpf Espectador");

        txtAdicionarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAdicionarValorActionPerformed(evt);
            }
        });

        btnInserirIngresso.setText("Inserir");
        btnInserirIngresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirIngressoActionPerformed(evt);
            }
        });

        btnInserirVerInformacoes.setText("Ver Informações");
        btnInserirVerInformacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirVerInformacoesActionPerformed(evt);
            }
        });

        btnInserirCadastrar.setText("Cadastrar");
        btnInserirCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbAdicionarEspectador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbAdicionarData, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAdicionarHora, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
                            .addComponent(txtAdicionarValor))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnInserirVerInformacoes))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnInserirCadastrar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnInserirIngresso)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdicionarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbAdicionarData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirVerInformacoes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAdicionarHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbAdicionarEspectador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserirCadastrar))
                .addGap(39, 39, 39)
                .addComponent(btnInserirIngresso)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(629, 325));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirIngressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirIngressoActionPerformed
        // TODO add your handling code here:
        Ingresso i = new Ingresso();
        LineUp lu = (LineUp) cbAdicionarData.getSelectedItem();
        Pessoa ps = (Pessoa) cbAdicionarEspectador.getSelectedItem();
        i.setValor(txtAdicionarValor.getText());
        i.setPertencedatalineup(lu.getData());
        i.setHoraEntrada(txtAdicionarHora.getText());
        if(i.getHoraEntrada().isEmpty()){
            i.setDataLineupEntrada(i.getHoraEntrada());
        }else{
            i.setDataLineupEntrada(lu.getData());
        }
        i.setCpfespectador(ps.getCpf());
           
        new IngressoDao().adicionar(i);

    }//GEN-LAST:event_btnInserirIngressoActionPerformed

    private void txtAdicionarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionarValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdicionarValorActionPerformed

    private void btnInserirVerInformacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirVerInformacoesActionPerformed
        try {
            // TODO add your handling code here:
            LineUp lu = (LineUp) cbAdicionarData.getSelectedItem();
            TelaSelecionarLineUp selecionarLineUp = new TelaSelecionarLineUp();
            selecionarLineUp.setVisible(true);
            ShowDao daoShow = new ShowDao();
            for(Show s: daoShow.readListar(lu.getData())){      
                cbselecionarShows.addItem(s);
            }
            BandaDao daoBanda = new BandaDao();
            for(Banda b: daoBanda.readListar(lu.getData())){
                cbselecionarBandas.addItem(b);
            }
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
            SimpleDateFormat formato2 = new SimpleDateFormat("dd/MM/yyyy");
            Date data = formato.parse(lu.getData());
            selecionarLineUp.txtSelecionarData.setText(formato2.format(data));
           
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnInserirVerInformacoesActionPerformed

    private void btnInserirCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirCadastrarActionPerformed
        // TODO add your handling code here:
        TelaAdicionarPessoa tela = new TelaAdicionarPessoa();
        tela.setVisible(true);
        tela.txtAddPessoaTipo.setText("Espectador");
        txtAddPessoaTipo.setEditable(false);
    }//GEN-LAST:event_btnInserirCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInserirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInserirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInserirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInserirIngresso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInserirIngresso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInserirCadastrar;
    private javax.swing.JButton btnInserirIngresso;
    private javax.swing.JButton btnInserirVerInformacoes;
    public static javax.swing.JComboBox<Object> cbAdicionarData;
    public static javax.swing.JComboBox<Object> cbAdicionarEspectador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtAdicionarHora;
    private javax.swing.JTextField txtAdicionarValor;
    // End of variables declaration//GEN-END:variables
}
