/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.bd.sistema.gui;
import br.edu.ifnmg.bd.sistema.entity.Funcionario;


/**
 *
 * @author annaj
 */
public class TelaPrincipal extends javax.swing.JFrame {
   /*private String usuario;

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }*/

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        this.setExtendedState(MAXIMIZED_BOTH); 
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuOcorrencia = new javax.swing.JMenu();
        menOcorrenciaListar = new javax.swing.JMenuItem();
        menOcorrenciaInserir = new javax.swing.JMenuItem();
        menOcorrenciaAtualizar = new javax.swing.JMenuItem();
        menOcorrenciaRemover = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menIngressoListar = new javax.swing.JMenuItem();
        menIngressoInserir = new javax.swing.JMenuItem();
        menIngressoAtualizar = new javax.swing.JMenuItem();
        menIngressoRemover = new javax.swing.JMenuItem();
        Relatorio = new javax.swing.JMenu();
        menuLineUp = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuOcorrencia.setText("Ocorrência");
        menuOcorrencia.setEnabled(false);
        menuOcorrencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOcorrenciaActionPerformed(evt);
            }
        });

        menOcorrenciaListar.setText("Listar");
        menOcorrenciaListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOcorrenciaListarActionPerformed(evt);
            }
        });
        menuOcorrencia.add(menOcorrenciaListar);

        menOcorrenciaInserir.setText("Inserir");
        menOcorrenciaInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOcorrenciaInserirActionPerformed(evt);
            }
        });
        menuOcorrencia.add(menOcorrenciaInserir);

        menOcorrenciaAtualizar.setText("Atualizar");
        menOcorrenciaAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOcorrenciaAtualizarActionPerformed(evt);
            }
        });
        menuOcorrencia.add(menOcorrenciaAtualizar);

        menOcorrenciaRemover.setText("Remover");
        menOcorrenciaRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menOcorrenciaRemoverActionPerformed(evt);
            }
        });
        menuOcorrencia.add(menOcorrenciaRemover);

        jMenuBar1.add(menuOcorrencia);

        jMenu2.setText("Ingresso");

        menIngressoListar.setText("Listar");
        menIngressoListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIngressoListarActionPerformed(evt);
            }
        });
        jMenu2.add(menIngressoListar);

        menIngressoInserir.setText("Inserir");
        menIngressoInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIngressoInserirActionPerformed(evt);
            }
        });
        jMenu2.add(menIngressoInserir);

        menIngressoAtualizar.setText("Atualizar");
        menIngressoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIngressoAtualizarActionPerformed(evt);
            }
        });
        jMenu2.add(menIngressoAtualizar);

        menIngressoRemover.setText("Remover");
        menIngressoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menIngressoRemoverActionPerformed(evt);
            }
        });
        jMenu2.add(menIngressoRemover);

        jMenuBar1.add(jMenu2);

        Relatorio.setText("Relatorio");
        Relatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatorioActionPerformed(evt);
            }
        });

        menuLineUp.setText("Line-Up");
        menuLineUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLineUpActionPerformed(evt);
            }
        });
        Relatorio.add(menuLineUp);

        jMenuBar1.add(Relatorio);

        jMenu3.setText("Sobre");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 382, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(679, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menOcorrenciaListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOcorrenciaListarActionPerformed
        // TODO add your handling code here:
        TelaListarOcorrencia listarOcorrencia = new TelaListarOcorrencia();
        listarOcorrencia.setVisible(true);
    }//GEN-LAST:event_menOcorrenciaListarActionPerformed

    private void menOcorrenciaInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOcorrenciaInserirActionPerformed
        // TODO add your handling code here:
        TelaInserirOcorrencia inserirOcorrencia = new TelaInserirOcorrencia();
        inserirOcorrencia.setVisible(true);
    }//GEN-LAST:event_menOcorrenciaInserirActionPerformed

    private void menuOcorrenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOcorrenciaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuOcorrenciaActionPerformed

    private void menOcorrenciaAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOcorrenciaAtualizarActionPerformed
        // TODO add your handling code here:
        TelaAtualizarOcorrencia atualizarOcorrencia = new TelaAtualizarOcorrencia();
        atualizarOcorrencia.setVisible(true);
    }//GEN-LAST:event_menOcorrenciaAtualizarActionPerformed

    private void menOcorrenciaRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menOcorrenciaRemoverActionPerformed
        // TODO add your handling code here:
        TelaRemoverOcorrencia removerOcorrencia = new TelaRemoverOcorrencia();
        removerOcorrencia.setVisible(true);
    }//GEN-LAST:event_menOcorrenciaRemoverActionPerformed

    private void menIngressoInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIngressoInserirActionPerformed
        // TODO add your handling code here:
        TelaInserirIngresso adicionarIngresso = new TelaInserirIngresso();
        adicionarIngresso.setVisible(true);
    }//GEN-LAST:event_menIngressoInserirActionPerformed

    private void menIngressoListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIngressoListarActionPerformed
        // TODO add your handling code here:
        TelaListarIngresso listarIngresso = new TelaListarIngresso();
        listarIngresso.setVisible(true);
    }//GEN-LAST:event_menIngressoListarActionPerformed

    private void menIngressoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIngressoAtualizarActionPerformed
        // TODO add your handling code here:
        TelaAtualizarIngresso atualizarIngresso = new TelaAtualizarIngresso();
        atualizarIngresso.setVisible(true);
        
    }//GEN-LAST:event_menIngressoAtualizarActionPerformed

    private void menIngressoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menIngressoRemoverActionPerformed
        // TODO add your handling code here:
        TelaRemoverIngresso removerIngresso = new TelaRemoverIngresso();
        removerIngresso.setVisible(true);
    }//GEN-LAST:event_menIngressoRemoverActionPerformed

    private void RelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatorioActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_RelatorioActionPerformed

    private void menuLineUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLineUpActionPerformed
        // TODO add your handling code here:
        TelaRelatorioLineUp relatorio = new TelaRelatorioLineUp();
        relatorio.setVisible(true);
    }//GEN-LAST:event_menuLineUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Relatorio;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menIngressoAtualizar;
    private javax.swing.JMenuItem menIngressoInserir;
    private javax.swing.JMenuItem menIngressoListar;
    private javax.swing.JMenuItem menIngressoRemover;
    private javax.swing.JMenuItem menOcorrenciaAtualizar;
    private javax.swing.JMenuItem menOcorrenciaInserir;
    private javax.swing.JMenuItem menOcorrenciaListar;
    private javax.swing.JMenuItem menOcorrenciaRemover;
    private javax.swing.JMenuItem menuLineUp;
    public static javax.swing.JMenu menuOcorrencia;
    // End of variables declaration//GEN-END:variables
}
